REM Autogenerated by LiteX / git: f98b288e9

quartus_map --read_settings_files=on  --write_settings_files=off omdazz_c4_platform -c omdazz_c4_platform
quartus_fit --read_settings_files=off --write_settings_files=off omdazz_c4_platform -c omdazz_c4_platform
quartus_asm --read_settings_files=off --write_settings_files=off omdazz_c4_platform -c omdazz_c4_platform
quartus_sta omdazz_c4_platform -c omdazz_c4_platform
if exist "omdazz_c4_platform.sof" (
    quartus_cpf -c omdazz_c4_platform.sof omdazz_c4_platform.rbf
)

if exist "omdazz_c4_platform.sof" (
    quartus_cpf -c -q "12.0MHz" -g 3.3 -n p omdazz_c4_platform.sof omdazz_c4_platform.svf
)
