// -----------------------------------------------------------------------------
// Auto-Generated by:        __   _ __      _  __
//                          / /  (_) /____ | |/_/
//                         / /__/ / __/ -_)>  <
//                        /____/_/\__/\__/_/|_|
//                     Build your hardware, easily!
//                   https://github.com/enjoy-digital/litex
//
// Filename   : omdazz_c4_platform.v
// Device     : EP4CE6E22C8
// LiteX sha1 : f98b288e9
// Date       : 2025-08-16 14:29:14
//------------------------------------------------------------------------------

`timescale 1ns / 1ps

//------------------------------------------------------------------------------
// Module
//------------------------------------------------------------------------------

module omdazz_c4_platform (
    input  wire          clk50,
    input  wire          gpio_in_gpio_in0,
    input  wire          gpio_in_gpio_in1,
    input  wire          gpio_in_gpio_in2,
    input  wire          gpio_in_gpio_in3,
    input  wire          gpio_in_gpio_in4,
    input  wire          gpio_in_gpio_in5,
    input  wire          gpio_in_gpio_in6,
    input  wire          gpio_in_gpio_in7,
    output wire          gpio_out_gpio_out0,
    output wire          gpio_out_gpio_out1,
    output wire          gpio_out_gpio_out2,
    output wire          gpio_out_gpio_out3,
    output wire          gpio_out_gpio_out4,
    output wire          gpio_out_gpio_out5,
    output wire          gpio_out_gpio_out6,
    output wire          gpio_out_gpio_out7,
    input  wire          reset,
    input  wire          serial_rx,
    output reg           serial_tx
);


//------------------------------------------------------------------------------
// Hierarchy
//------------------------------------------------------------------------------

/*
BaseSoC
|___ bus (SoCBusHandler)
|    |___ _interconnect (InterconnectShared)
|    |    |___ arbiter (Arbiter)
|    |    |    |___ rr (RoundRobin)
|    |    |___ decoder (Decoder)
|    |    |___ timeout (Timeout)
|    |    |    |___ waittimer_0* (WaitTimer)
|___ csr (SoCCSRHandler)
|___ irq (SoCIRQHandler)
|___ ctrl (SoCController)
|___ cpu (SERV)
|    |___ [serv_rf_top]
|___ rom (SRAM)
|___ sram (SRAM)
|___ uart_phy (RS232PHY)
|    |___ tx (RS232PHYTX)
|    |    |___ clk_phase_accum (RS232ClkPhaseAccum)
|    |    |___ fsm (FSM)
|    |___ rx (RS232PHYRX)
|    |    |___ clk_phase_accum (RS232ClkPhaseAccum)
|    |    |___ fsm (FSM)
|___ uart (UART)
|    |___ ev (EventManager)
|    |    |___ eventsourceprocess_0* (EventSourceProcess)
|    |    |___ eventsourceprocess_1* (EventSourceProcess)
|    |___ tx_fifo (SyncFIFO)
|    |    |___ fifo (SyncFIFOBuffered)
|    |    |    |___ fifo (SyncFIFO)
|    |___ rx_fifo (SyncFIFO)
|    |    |___ fifo (SyncFIFOBuffered)
|    |    |    |___ fifo (SyncFIFO)
|___ timer0 (Timer)
|    |___ ev (EventManager)
|    |    |___ eventsourceprocess_0* (EventSourceProcess)
|___ gpio_in (GPIOIn)
|___ gpio_out (GPIOOut)
|___ csr_bridge (Wishbone2CSR)
|    |___ fsm (FSM)
|___ csr_bankarray (CSRBankArray)
|    |___ csrbank_0* (CSRBank)
|    |    |___ csrstorage_0* (CSRStorage)
|    |    |___ csrstorage_1* (CSRStorage)
|    |    |___ csrstatus_0* (CSRStatus)
|    |___ csrbank_1* (CSRBank)
|    |    |___ csrstatus_0* (CSRStatus)
|    |___ csrbank_2* (CSRBank)
|    |    |___ csrstorage_0* (CSRStorage)
|    |___ csrbank_3* (CSRBank)
|    |    |___ csrstorage_0* (CSRStorage)
|    |    |___ csrstorage_1* (CSRStorage)
|    |    |___ csrstorage_2* (CSRStorage)
|    |    |___ csrstorage_3* (CSRStorage)
|    |    |___ csrstatus_0* (CSRStatus)
|    |    |___ csrstatus_1* (CSRStatus)
|    |    |___ csrstatus_2* (CSRStatus)
|    |    |___ csrstorage_4* (CSRStorage)
|    |___ csrbank_4* (CSRBank)
|    |    |___ csrstatus_0* (CSRStatus)
|    |    |___ csrstatus_1* (CSRStatus)
|    |    |___ csrstatus_2* (CSRStatus)
|    |    |___ csrstatus_3* (CSRStatus)
|    |    |___ csrstorage_0* (CSRStorage)
|    |    |___ csrstatus_4* (CSRStatus)
|    |    |___ csrstatus_5* (CSRStatus)
|___ csr_interconnect (InterconnectShared)
|___ [DFF]
|___ [DFF]
* : Generated name.
[]: BlackBox.
*/

//------------------------------------------------------------------------------
// Signals
//------------------------------------------------------------------------------

wire   [13:0] adr;
wire          ars_cd_sys_rst_meta;
wire   [12:0] basesoc_adr;
reg           basesoc_adr_burst = 1'd0;
wire   [31:0] basesoc_dat_r;
reg           basesoc_ram_bus_ack = 1'd0;
wire   [29:0] basesoc_ram_bus_adr;
wire    [1:0] basesoc_ram_bus_bte;
wire    [2:0] basesoc_ram_bus_cti;
wire          basesoc_ram_bus_cyc;
wire   [31:0] basesoc_ram_bus_dat_r;
wire   [31:0] basesoc_ram_bus_dat_w;
reg           basesoc_ram_bus_err = 1'd0;
wire    [3:0] basesoc_ram_bus_sel;
wire          basesoc_ram_bus_stb;
wire          basesoc_ram_bus_we;
wire          bus_error;
reg    [31:0] bus_errors = 32'd0;
reg           bus_errors_re = 1'd0;
wire   [31:0] bus_errors_status;
wire          bus_errors_we;
reg    [19:0] count = 20'd1000000;
wire          cpu_rst;
wire   [31:0] csrbank0_bus_errors_r;
reg           csrbank0_bus_errors_re = 1'd0;
wire   [31:0] csrbank0_bus_errors_w;
reg           csrbank0_bus_errors_we = 1'd0;
wire    [1:0] csrbank0_reset0_r;
reg           csrbank0_reset0_re = 1'd0;
wire    [1:0] csrbank0_reset0_w;
reg           csrbank0_reset0_we = 1'd0;
wire   [31:0] csrbank0_scratch0_r;
reg           csrbank0_scratch0_re = 1'd0;
wire   [31:0] csrbank0_scratch0_w;
reg           csrbank0_scratch0_we = 1'd0;
wire          csrbank0_sel;
wire    [7:0] csrbank1_in_r;
reg           csrbank1_in_re = 1'd0;
wire    [7:0] csrbank1_in_w;
reg           csrbank1_in_we = 1'd0;
wire          csrbank1_sel;
wire    [7:0] csrbank2_out0_r;
reg           csrbank2_out0_re = 1'd0;
wire    [7:0] csrbank2_out0_w;
reg           csrbank2_out0_we = 1'd0;
wire          csrbank2_sel;
wire          csrbank3_en0_r;
reg           csrbank3_en0_re = 1'd0;
wire          csrbank3_en0_w;
reg           csrbank3_en0_we = 1'd0;
wire          csrbank3_ev_enable0_r;
reg           csrbank3_ev_enable0_re = 1'd0;
wire          csrbank3_ev_enable0_w;
reg           csrbank3_ev_enable0_we = 1'd0;
wire          csrbank3_ev_pending_r;
reg           csrbank3_ev_pending_re = 1'd0;
wire          csrbank3_ev_pending_w;
reg           csrbank3_ev_pending_we = 1'd0;
wire          csrbank3_ev_status_r;
reg           csrbank3_ev_status_re = 1'd0;
wire          csrbank3_ev_status_w;
reg           csrbank3_ev_status_we = 1'd0;
wire   [31:0] csrbank3_load0_r;
reg           csrbank3_load0_re = 1'd0;
wire   [31:0] csrbank3_load0_w;
reg           csrbank3_load0_we = 1'd0;
wire   [31:0] csrbank3_reload0_r;
reg           csrbank3_reload0_re = 1'd0;
wire   [31:0] csrbank3_reload0_w;
reg           csrbank3_reload0_we = 1'd0;
wire          csrbank3_sel;
wire          csrbank3_update_value0_r;
reg           csrbank3_update_value0_re = 1'd0;
wire          csrbank3_update_value0_w;
reg           csrbank3_update_value0_we = 1'd0;
wire   [31:0] csrbank3_value_r;
reg           csrbank3_value_re = 1'd0;
wire   [31:0] csrbank3_value_w;
reg           csrbank3_value_we = 1'd0;
wire    [1:0] csrbank4_ev_enable0_r;
reg           csrbank4_ev_enable0_re = 1'd0;
wire    [1:0] csrbank4_ev_enable0_w;
reg           csrbank4_ev_enable0_we = 1'd0;
wire    [1:0] csrbank4_ev_pending_r;
reg           csrbank4_ev_pending_re = 1'd0;
wire    [1:0] csrbank4_ev_pending_w;
reg           csrbank4_ev_pending_we = 1'd0;
wire    [1:0] csrbank4_ev_status_r;
reg           csrbank4_ev_status_re = 1'd0;
wire    [1:0] csrbank4_ev_status_w;
reg           csrbank4_ev_status_we = 1'd0;
wire          csrbank4_rxempty_r;
reg           csrbank4_rxempty_re = 1'd0;
wire          csrbank4_rxempty_w;
reg           csrbank4_rxempty_we = 1'd0;
wire          csrbank4_rxfull_r;
reg           csrbank4_rxfull_re = 1'd0;
wire          csrbank4_rxfull_w;
reg           csrbank4_rxfull_we = 1'd0;
wire          csrbank4_sel;
wire          csrbank4_txempty_r;
reg           csrbank4_txempty_re = 1'd0;
wire          csrbank4_txempty_w;
reg           csrbank4_txempty_we = 1'd0;
wire          csrbank4_txfull_r;
reg           csrbank4_txfull_re = 1'd0;
wire          csrbank4_txfull_w;
reg           csrbank4_txfull_we = 1'd0;
wire   [31:0] dat_r;
wire   [31:0] dat_w;
wire          dbus_ack;
wire   [31:0] dbus_adr;
reg     [1:0] dbus_bte = 2'd0;
reg     [2:0] dbus_cti = 3'd0;
wire          dbus_cyc;
wire   [31:0] dbus_dat_r;
wire   [31:0] dbus_dat_w;
wire          dbus_err;
wire    [3:0] dbus_sel;
wire          dbus_stb;
wire          dbus_we;
wire          done;
reg           error = 1'd0;
reg           gpio_in_re = 1'd0;
wire    [7:0] gpio_in_status;
wire          gpio_in_we;
reg           gpio_out_re = 1'd0;
reg     [7:0] gpio_out_storage = 8'd0;
reg           grant = 1'd0;
wire          ibus_ack;
wire   [31:0] ibus_adr;
reg     [1:0] ibus_bte = 2'd0;
reg     [2:0] ibus_cti = 3'd0;
wire          ibus_cyc;
wire   [31:0] ibus_dat_r;
reg    [31:0] ibus_dat_w = 32'd0;
wire          ibus_err;
wire    [3:0] ibus_sel;
wire          ibus_stb;
reg           ibus_we = 1'd0;
reg           interface0_ack = 1'd0;
wire          interface0_adapted_interface_ack;
wire   [29:0] interface0_adapted_interface_adr;
wire    [1:0] interface0_adapted_interface_bte;
wire    [2:0] interface0_adapted_interface_cti;
wire          interface0_adapted_interface_cyc;
wire   [31:0] interface0_adapted_interface_dat_r;
wire   [31:0] interface0_adapted_interface_dat_w;
wire          interface0_adapted_interface_err;
wire    [3:0] interface0_adapted_interface_sel;
wire          interface0_adapted_interface_stb;
wire          interface0_adapted_interface_we;
wire   [29:0] interface0_adr0;
wire   [13:0] interface0_adr1;
wire    [1:0] interface0_bte;
wire    [2:0] interface0_cti;
wire          interface0_cyc;
reg    [31:0] interface0_dat_r0 = 32'd0;
reg    [31:0] interface0_dat_r1 = 32'd0;
wire   [31:0] interface0_dat_w0;
wire   [31:0] interface0_dat_w1;
reg           interface0_err = 1'd0;
wire          interface0_re;
wire    [3:0] interface0_sel;
wire          interface0_stb;
wire          interface0_we0;
wire          interface0_we1;
wire          interface1_adapted_interface_ack;
wire   [29:0] interface1_adapted_interface_adr;
wire    [1:0] interface1_adapted_interface_bte;
wire    [2:0] interface1_adapted_interface_cti;
wire          interface1_adapted_interface_cyc;
wire   [31:0] interface1_adapted_interface_dat_r;
wire   [31:0] interface1_adapted_interface_dat_w;
wire          interface1_adapted_interface_err;
wire    [3:0] interface1_adapted_interface_sel;
wire          interface1_adapted_interface_stb;
wire          interface1_adapted_interface_we;
reg    [13:0] interface1_adr0 = 14'd0;
wire   [13:0] interface1_adr1;
wire   [31:0] interface1_dat_r0;
reg    [31:0] interface1_dat_r1 = 32'd0;
reg    [31:0] interface1_dat_w0 = 32'd0;
wire   [31:0] interface1_dat_w1;
reg           interface1_re0 = 1'd0;
wire          interface1_re1;
reg           interface1_we0 = 1'd0;
wire          interface1_we1;
wire   [13:0] interface2_adr;
reg    [31:0] interface2_dat_r = 32'd0;
wire   [31:0] interface2_dat_w;
wire          interface2_re;
wire          interface2_we;
wire   [13:0] interface3_adr;
reg    [31:0] interface3_dat_r = 32'd0;
wire   [31:0] interface3_dat_w;
wire          interface3_re;
wire          interface3_we;
wire   [13:0] interface4_adr;
reg    [31:0] interface4_dat_r = 32'd0;
wire   [31:0] interface4_dat_w;
wire          interface4_re;
wire          interface4_we;
reg     [2:0] master = 3'd0;
reg           multiregimpl00 = 1'd0;
reg           multiregimpl01 = 1'd0;
reg     [7:0] multiregimpl10 = 8'd0;
reg     [7:0] multiregimpl11 = 8'd0;
reg           next_state = 1'd0;
wire    [8:0] ram_adr;
reg           ram_adr_burst = 1'd0;
reg           ram_bus_ram_bus_ack = 1'd0;
wire   [29:0] ram_bus_ram_bus_adr;
wire    [1:0] ram_bus_ram_bus_bte;
wire    [2:0] ram_bus_ram_bus_cti;
wire          ram_bus_ram_bus_cyc;
wire   [31:0] ram_bus_ram_bus_dat_r;
wire   [31:0] ram_bus_ram_bus_dat_w;
reg           ram_bus_ram_bus_err = 1'd0;
wire    [3:0] ram_bus_ram_bus_sel;
wire          ram_bus_ram_bus_stb;
wire          ram_bus_ram_bus_we;
wire   [31:0] ram_dat_r;
wire   [31:0] ram_dat_w;
reg     [3:0] ram_we = 4'd0;
wire          re;
wire    [1:0] request;
wire          reset_1;
reg           reset_re = 1'd0;
reg     [1:0] reset_storage = 2'd0;
reg           rs232phyrx_next_state = 1'd0;
reg           rs232phyrx_state = 1'd0;
reg           rs232phytx_next_state = 1'd0;
reg           rs232phytx_state = 1'd0;
reg     [3:0] rx_count = 4'd0;
reg     [3:0] rx_count_rs232phyrx_next_value0 = 4'd0;
reg           rx_count_rs232phyrx_next_value_ce0 = 1'd0;
reg     [7:0] rx_data = 8'd0;
reg     [7:0] rx_data_rs232phyrx_next_value1 = 8'd0;
reg           rx_data_rs232phyrx_next_value_ce1 = 1'd0;
reg           rx_enable = 1'd0;
reg    [31:0] rx_phase = 32'd0;
wire          rx_rx;
reg           rx_rx_d = 1'd0;
reg           rx_source_first = 1'd0;
reg           rx_source_last = 1'd0;
reg     [7:0] rx_source_payload_data = 8'd0;
wire          rx_source_ready;
reg           rx_source_valid = 1'd0;
reg           rx_tick = 1'd0;
reg           scratch_re = 1'd0;
reg    [31:0] scratch_storage = 32'd305419896;
reg    [29:0] self0 = 30'd0;
reg    [31:0] self1 = 32'd0;
reg     [3:0] self2 = 4'd0;
reg           self3 = 1'd0;
reg           self4 = 1'd0;
reg           self5 = 1'd0;
reg     [2:0] self6 = 3'd0;
reg     [1:0] self7 = 2'd0;
reg           serial_tx_rs232phytx_next_value1 = 1'd0;
reg           serial_tx_rs232phytx_next_value_ce1 = 1'd0;
reg           shared_ack = 1'd0;
wire   [29:0] shared_adr;
wire    [1:0] shared_bte;
wire    [2:0] shared_cti;
wire          shared_cyc;
reg    [31:0] shared_dat_r = 32'd0;
wire   [31:0] shared_dat_w;
wire          shared_err;
wire    [3:0] shared_sel;
wire          shared_stb;
wire          shared_we;
reg     [2:0] slaves = 3'd0;
reg           soc_rst = 1'd0;
reg           state = 1'd0;
wire          sys_clk;
wire          sys_rst;
reg           timer_en_re = 1'd0;
reg           timer_en_storage = 1'd0;
reg           timer_enable_re = 1'd0;
reg           timer_enable_storage = 1'd0;
wire          timer_irq;
reg           timer_load_re = 1'd0;
reg    [31:0] timer_load_storage = 32'd0;
reg           timer_pending_r = 1'd0;
reg           timer_pending_re = 1'd0;
wire          timer_pending_status;
wire          timer_pending_we;
reg           timer_reload_re = 1'd0;
reg    [31:0] timer_reload_storage = 32'd0;
reg           timer_status_re = 1'd0;
wire          timer_status_status;
wire          timer_status_we;
reg           timer_update_value_re = 1'd0;
reg           timer_update_value_storage = 1'd0;
reg    [31:0] timer_value = 32'd0;
reg           timer_value_re = 1'd0;
reg    [31:0] timer_value_status = 32'd0;
wire          timer_value_we;
wire          timer_zero0;
wire          timer_zero1;
wire          timer_zero2;
reg           timer_zero_clear = 1'd0;
reg           timer_zero_pending = 1'd0;
wire          timer_zero_status;
wire          timer_zero_trigger;
reg           timer_zero_trigger_d = 1'd0;
reg     [3:0] tx_count = 4'd0;
reg     [3:0] tx_count_rs232phytx_next_value0 = 4'd0;
reg           tx_count_rs232phytx_next_value_ce0 = 1'd0;
reg     [7:0] tx_data = 8'd0;
reg     [7:0] tx_data_rs232phytx_next_value2 = 8'd0;
reg           tx_data_rs232phytx_next_value_ce2 = 1'd0;
reg           tx_enable = 1'd0;
reg    [31:0] tx_phase = 32'd0;
wire          tx_sink_first;
wire          tx_sink_last;
wire    [7:0] tx_sink_payload_data;
reg           tx_sink_ready = 1'd0;
wire          tx_sink_valid;
reg           tx_tick = 1'd0;
reg           uart_enable_re = 1'd0;
reg     [1:0] uart_enable_storage = 2'd0;
wire          uart_irq;
reg     [1:0] uart_pending_r = 2'd0;
reg           uart_pending_re = 1'd0;
reg     [1:0] uart_pending_status = 2'd0;
wire          uart_pending_we;
wire          uart_rx0;
wire          uart_rx1;
wire          uart_rx2;
reg           uart_rx_clear = 1'd0;
reg     [3:0] uart_rx_fifo_consume = 4'd0;
wire          uart_rx_fifo_do_read;
wire          uart_rx_fifo_fifo_in_first;
wire          uart_rx_fifo_fifo_in_last;
wire    [7:0] uart_rx_fifo_fifo_in_payload_data;
wire          uart_rx_fifo_fifo_out_first;
wire          uart_rx_fifo_fifo_out_last;
wire    [7:0] uart_rx_fifo_fifo_out_payload_data;
reg     [4:0] uart_rx_fifo_level0 = 5'd0;
wire    [4:0] uart_rx_fifo_level1;
reg     [3:0] uart_rx_fifo_produce = 4'd0;
wire    [3:0] uart_rx_fifo_rdport_adr;
wire    [9:0] uart_rx_fifo_rdport_dat_r;
wire          uart_rx_fifo_rdport_re;
wire          uart_rx_fifo_re;
reg           uart_rx_fifo_readable = 1'd0;
reg           uart_rx_fifo_replace = 1'd0;
wire          uart_rx_fifo_sink_first;
wire          uart_rx_fifo_sink_last;
wire    [7:0] uart_rx_fifo_sink_payload_data;
wire          uart_rx_fifo_sink_ready;
wire          uart_rx_fifo_sink_valid;
wire          uart_rx_fifo_source_first;
wire          uart_rx_fifo_source_last;
wire    [7:0] uart_rx_fifo_source_payload_data;
wire          uart_rx_fifo_source_ready;
wire          uart_rx_fifo_source_valid;
wire    [9:0] uart_rx_fifo_syncfifo_din;
wire    [9:0] uart_rx_fifo_syncfifo_dout;
wire          uart_rx_fifo_syncfifo_re;
wire          uart_rx_fifo_syncfifo_readable;
wire          uart_rx_fifo_syncfifo_we;
wire          uart_rx_fifo_syncfifo_writable;
reg     [3:0] uart_rx_fifo_wrport_adr = 4'd0;
wire    [9:0] uart_rx_fifo_wrport_dat_r;
wire    [9:0] uart_rx_fifo_wrport_dat_w;
wire          uart_rx_fifo_wrport_we;
reg           uart_rx_pending = 1'd0;
wire          uart_rx_status;
wire          uart_rx_trigger;
reg           uart_rx_trigger_d = 1'd0;
reg           uart_rxempty_re = 1'd0;
wire          uart_rxempty_status;
wire          uart_rxempty_we;
reg           uart_rxfull_re = 1'd0;
wire          uart_rxfull_status;
wire          uart_rxfull_we;
wire    [7:0] uart_rxtx_r;
reg           uart_rxtx_re = 1'd0;
wire    [7:0] uart_rxtx_w;
reg           uart_rxtx_we = 1'd0;
reg           uart_status_re = 1'd0;
reg     [1:0] uart_status_status = 2'd0;
wire          uart_status_we;
wire          uart_tx0;
wire          uart_tx1;
wire          uart_tx2;
reg           uart_tx_clear = 1'd0;
reg     [3:0] uart_tx_fifo_consume = 4'd0;
wire          uart_tx_fifo_do_read;
wire          uart_tx_fifo_fifo_in_first;
wire          uart_tx_fifo_fifo_in_last;
wire    [7:0] uart_tx_fifo_fifo_in_payload_data;
wire          uart_tx_fifo_fifo_out_first;
wire          uart_tx_fifo_fifo_out_last;
wire    [7:0] uart_tx_fifo_fifo_out_payload_data;
reg     [4:0] uart_tx_fifo_level0 = 5'd0;
wire    [4:0] uart_tx_fifo_level1;
reg     [3:0] uart_tx_fifo_produce = 4'd0;
wire    [3:0] uart_tx_fifo_rdport_adr;
wire    [9:0] uart_tx_fifo_rdport_dat_r;
wire          uart_tx_fifo_rdport_re;
wire          uart_tx_fifo_re;
reg           uart_tx_fifo_readable = 1'd0;
reg           uart_tx_fifo_replace = 1'd0;
reg           uart_tx_fifo_sink_first = 1'd0;
reg           uart_tx_fifo_sink_last = 1'd0;
wire    [7:0] uart_tx_fifo_sink_payload_data;
wire          uart_tx_fifo_sink_ready;
wire          uart_tx_fifo_sink_valid;
wire          uart_tx_fifo_source_first;
wire          uart_tx_fifo_source_last;
wire    [7:0] uart_tx_fifo_source_payload_data;
wire          uart_tx_fifo_source_ready;
wire          uart_tx_fifo_source_valid;
wire    [9:0] uart_tx_fifo_syncfifo_din;
wire    [9:0] uart_tx_fifo_syncfifo_dout;
wire          uart_tx_fifo_syncfifo_re;
wire          uart_tx_fifo_syncfifo_readable;
wire          uart_tx_fifo_syncfifo_we;
wire          uart_tx_fifo_syncfifo_writable;
reg     [3:0] uart_tx_fifo_wrport_adr = 4'd0;
wire    [9:0] uart_tx_fifo_wrport_dat_r;
wire    [9:0] uart_tx_fifo_wrport_dat_w;
wire          uart_tx_fifo_wrport_we;
reg           uart_tx_pending = 1'd0;
wire          uart_tx_status;
wire          uart_tx_trigger;
reg           uart_tx_trigger_d = 1'd0;
reg           uart_txempty_re = 1'd0;
wire          uart_txempty_status;
wire          uart_txempty_we;
reg           uart_txfull_re = 1'd0;
wire          uart_txfull_status;
wire          uart_txfull_we;
wire          uart_uart_sink_first;
wire          uart_uart_sink_last;
wire    [7:0] uart_uart_sink_payload_data;
wire          uart_uart_sink_ready;
wire          uart_uart_sink_valid;
wire          uart_uart_source_first;
wire          uart_uart_source_last;
wire    [7:0] uart_uart_source_payload_data;
wire          uart_uart_source_ready;
wire          uart_uart_source_valid;
wire          wait_1;
wire          we;

//------------------------------------------------------------------------------
// Combinatorial Logic
//------------------------------------------------------------------------------

assign sys_clk = clk50;
assign reset_1 = (soc_rst | cpu_rst);
assign bus_error = error;
assign interface0_adapted_interface_dat_w = ibus_dat_w;
assign ibus_dat_r = interface0_adapted_interface_dat_r;
assign interface0_adapted_interface_sel = ibus_sel;
assign interface0_adapted_interface_cyc = ibus_cyc;
assign interface0_adapted_interface_stb = ibus_stb;
assign ibus_ack = interface0_adapted_interface_ack;
assign interface0_adapted_interface_we = ibus_we;
assign interface0_adapted_interface_cti = ibus_cti;
assign interface0_adapted_interface_bte = ibus_bte;
assign ibus_err = interface0_adapted_interface_err;
assign interface0_adapted_interface_adr = ibus_adr[31:2];
assign interface1_adapted_interface_dat_w = dbus_dat_w;
assign dbus_dat_r = interface1_adapted_interface_dat_r;
assign interface1_adapted_interface_sel = dbus_sel;
assign interface1_adapted_interface_cyc = dbus_cyc;
assign interface1_adapted_interface_stb = dbus_stb;
assign dbus_ack = interface1_adapted_interface_ack;
assign interface1_adapted_interface_we = dbus_we;
assign interface1_adapted_interface_cti = dbus_cti;
assign interface1_adapted_interface_bte = dbus_bte;
assign dbus_err = interface1_adapted_interface_err;
assign interface1_adapted_interface_adr = dbus_adr[31:2];
assign shared_adr = self0;
assign shared_dat_w = self1;
assign shared_sel = self2;
assign shared_cyc = self3;
assign shared_stb = self4;
assign shared_we = self5;
assign shared_cti = self6;
assign shared_bte = self7;
assign interface0_adapted_interface_dat_r = shared_dat_r;
assign interface1_adapted_interface_dat_r = shared_dat_r;
assign interface0_adapted_interface_ack = (shared_ack & (grant == 1'd0));
assign interface1_adapted_interface_ack = (shared_ack & (grant == 1'd1));
assign interface0_adapted_interface_err = (shared_err & (grant == 1'd0));
assign interface1_adapted_interface_err = (shared_err & (grant == 1'd1));
assign request = {interface1_adapted_interface_cyc, interface0_adapted_interface_cyc};
always @(*) begin
    master <= 3'd0;
    master[0] <= (shared_adr[29:13] == 1'd0);
    master[1] <= (shared_adr[29:9] == 14'd8192);
    master[2] <= (shared_adr[29:14] == 16'd33280);
end
assign basesoc_ram_bus_adr = shared_adr;
assign basesoc_ram_bus_dat_w = shared_dat_w;
assign basesoc_ram_bus_sel = shared_sel;
assign basesoc_ram_bus_stb = shared_stb;
assign basesoc_ram_bus_we = shared_we;
assign basesoc_ram_bus_cti = shared_cti;
assign basesoc_ram_bus_bte = shared_bte;
assign ram_bus_ram_bus_adr = shared_adr;
assign ram_bus_ram_bus_dat_w = shared_dat_w;
assign ram_bus_ram_bus_sel = shared_sel;
assign ram_bus_ram_bus_stb = shared_stb;
assign ram_bus_ram_bus_we = shared_we;
assign ram_bus_ram_bus_cti = shared_cti;
assign ram_bus_ram_bus_bte = shared_bte;
assign interface0_adr0 = shared_adr;
assign interface0_dat_w0 = shared_dat_w;
assign interface0_sel = shared_sel;
assign interface0_stb = shared_stb;
assign interface0_we0 = shared_we;
assign interface0_cti = shared_cti;
assign interface0_bte = shared_bte;
assign basesoc_ram_bus_cyc = (shared_cyc & master[0]);
assign ram_bus_ram_bus_cyc = (shared_cyc & master[1]);
assign interface0_cyc = (shared_cyc & master[2]);
assign shared_err = ((basesoc_ram_bus_err | ram_bus_ram_bus_err) | interface0_err);
assign wait_1 = ((shared_stb & shared_cyc) & (~shared_ack));
always @(*) begin
    error <= 1'd0;
    shared_ack <= 1'd0;
    shared_dat_r <= 32'd0;
    shared_ack <= ((basesoc_ram_bus_ack | ram_bus_ram_bus_ack) | interface0_ack);
    shared_dat_r <= ((({32{slaves[0]}} & basesoc_ram_bus_dat_r) | ({32{slaves[1]}} & ram_bus_ram_bus_dat_r)) | ({32{slaves[2]}} & interface0_dat_r0));
    if (done) begin
        shared_dat_r <= 32'd4294967295;
        shared_ack <= 1'd1;
        error <= 1'd1;
    end
end
assign done = (count == 1'd0);
assign bus_errors_status = bus_errors;
assign ibus_stb = ibus_cyc;
assign ibus_sel = 4'd15;
assign dbus_stb = dbus_cyc;
assign basesoc_adr = basesoc_ram_bus_adr[12:0];
assign basesoc_ram_bus_dat_r = basesoc_dat_r;
always @(*) begin
    ram_we <= 4'd0;
    ram_we[0] <= (((ram_bus_ram_bus_cyc & ram_bus_ram_bus_stb) & ram_bus_ram_bus_we) & ram_bus_ram_bus_sel[0]);
    ram_we[1] <= (((ram_bus_ram_bus_cyc & ram_bus_ram_bus_stb) & ram_bus_ram_bus_we) & ram_bus_ram_bus_sel[1]);
    ram_we[2] <= (((ram_bus_ram_bus_cyc & ram_bus_ram_bus_stb) & ram_bus_ram_bus_we) & ram_bus_ram_bus_sel[2]);
    ram_we[3] <= (((ram_bus_ram_bus_cyc & ram_bus_ram_bus_stb) & ram_bus_ram_bus_we) & ram_bus_ram_bus_sel[3]);
end
assign ram_adr = ram_bus_ram_bus_adr[8:0];
assign ram_bus_ram_bus_dat_r = ram_dat_r;
assign ram_dat_w = ram_bus_ram_bus_dat_w;
always @(*) begin
    rs232phytx_next_state <= 1'd0;
    serial_tx_rs232phytx_next_value1 <= 1'd0;
    serial_tx_rs232phytx_next_value_ce1 <= 1'd0;
    tx_count_rs232phytx_next_value0 <= 4'd0;
    tx_count_rs232phytx_next_value_ce0 <= 1'd0;
    tx_data_rs232phytx_next_value2 <= 8'd0;
    tx_data_rs232phytx_next_value_ce2 <= 1'd0;
    tx_enable <= 1'd0;
    tx_sink_ready <= 1'd0;
    rs232phytx_next_state <= rs232phytx_state;
    case (rs232phytx_state)
        1'd1: begin
            tx_enable <= 1'd1;
            if (tx_tick) begin
                serial_tx_rs232phytx_next_value1 <= tx_data[0];
                serial_tx_rs232phytx_next_value_ce1 <= 1'd1;
                tx_count_rs232phytx_next_value0 <= (tx_count + 1'd1);
                tx_count_rs232phytx_next_value_ce0 <= 1'd1;
                tx_data_rs232phytx_next_value2 <= {1'd1, tx_data[7:1]};
                tx_data_rs232phytx_next_value_ce2 <= 1'd1;
                if ((tx_count == 4'd9)) begin
                    tx_sink_ready <= 1'd1;
                    rs232phytx_next_state <= 1'd0;
                end
            end
        end
        default: begin
            tx_count_rs232phytx_next_value0 <= 1'd0;
            tx_count_rs232phytx_next_value_ce0 <= 1'd1;
            serial_tx_rs232phytx_next_value1 <= 1'd1;
            serial_tx_rs232phytx_next_value_ce1 <= 1'd1;
            if (tx_sink_valid) begin
                serial_tx_rs232phytx_next_value1 <= 1'd0;
                serial_tx_rs232phytx_next_value_ce1 <= 1'd1;
                tx_data_rs232phytx_next_value2 <= tx_sink_payload_data;
                tx_data_rs232phytx_next_value_ce2 <= 1'd1;
                rs232phytx_next_state <= 1'd1;
            end
        end
    endcase
end
always @(*) begin
    rs232phyrx_next_state <= 1'd0;
    rx_count_rs232phyrx_next_value0 <= 4'd0;
    rx_count_rs232phyrx_next_value_ce0 <= 1'd0;
    rx_data_rs232phyrx_next_value1 <= 8'd0;
    rx_data_rs232phyrx_next_value_ce1 <= 1'd0;
    rx_enable <= 1'd0;
    rx_source_payload_data <= 8'd0;
    rx_source_valid <= 1'd0;
    rs232phyrx_next_state <= rs232phyrx_state;
    case (rs232phyrx_state)
        1'd1: begin
            rx_enable <= 1'd1;
            if (rx_tick) begin
                rx_count_rs232phyrx_next_value0 <= (rx_count + 1'd1);
                rx_count_rs232phyrx_next_value_ce0 <= 1'd1;
                rx_data_rs232phyrx_next_value1 <= {rx_rx, rx_data[7:1]};
                rx_data_rs232phyrx_next_value_ce1 <= 1'd1;
                if ((rx_count == 4'd9)) begin
                    rx_source_valid <= (rx_rx == 1'd1);
                    rx_source_payload_data <= rx_data;
                    rs232phyrx_next_state <= 1'd0;
                end
            end
        end
        default: begin
            rx_count_rs232phyrx_next_value0 <= 1'd0;
            rx_count_rs232phyrx_next_value_ce0 <= 1'd1;
            if (((rx_rx == 1'd0) & (rx_rx_d == 1'd1))) begin
                rs232phyrx_next_state <= 1'd1;
            end
        end
    endcase
end
assign uart_uart_sink_valid = rx_source_valid;
assign rx_source_ready = uart_uart_sink_ready;
assign uart_uart_sink_first = rx_source_first;
assign uart_uart_sink_last = rx_source_last;
assign uart_uart_sink_payload_data = rx_source_payload_data;
assign tx_sink_valid = uart_uart_source_valid;
assign uart_uart_source_ready = tx_sink_ready;
assign tx_sink_first = uart_uart_source_first;
assign tx_sink_last = uart_uart_source_last;
assign tx_sink_payload_data = uart_uart_source_payload_data;
assign uart_tx_fifo_sink_valid = uart_rxtx_re;
assign uart_tx_fifo_sink_payload_data = uart_rxtx_r;
assign uart_uart_source_valid = uart_tx_fifo_source_valid;
assign uart_tx_fifo_source_ready = uart_uart_source_ready;
assign uart_uart_source_first = uart_tx_fifo_source_first;
assign uart_uart_source_last = uart_tx_fifo_source_last;
assign uart_uart_source_payload_data = uart_tx_fifo_source_payload_data;
assign uart_txfull_status = (~uart_tx_fifo_sink_ready);
assign uart_txempty_status = (~uart_tx_fifo_source_valid);
assign uart_tx_trigger = uart_tx_fifo_sink_ready;
assign uart_rx_fifo_sink_valid = uart_uart_sink_valid;
assign uart_uart_sink_ready = uart_rx_fifo_sink_ready;
assign uart_rx_fifo_sink_first = uart_uart_sink_first;
assign uart_rx_fifo_sink_last = uart_uart_sink_last;
assign uart_rx_fifo_sink_payload_data = uart_uart_sink_payload_data;
assign uart_rxtx_w = uart_rx_fifo_source_payload_data;
assign uart_rx_fifo_source_ready = (uart_rx_clear | (1'd0 & uart_rxtx_we));
assign uart_rxempty_status = (~uart_rx_fifo_source_valid);
assign uart_rxfull_status = (~uart_rx_fifo_sink_ready);
assign uart_rx_trigger = uart_rx_fifo_source_valid;
assign uart_tx0 = uart_tx_status;
assign uart_tx1 = uart_tx_pending;
always @(*) begin
    uart_tx_clear <= 1'd0;
    if ((uart_pending_re & uart_pending_r[0])) begin
        uart_tx_clear <= 1'd1;
    end
end
assign uart_rx0 = uart_rx_status;
assign uart_rx1 = uart_rx_pending;
always @(*) begin
    uart_rx_clear <= 1'd0;
    if ((uart_pending_re & uart_pending_r[1])) begin
        uart_rx_clear <= 1'd1;
    end
end
assign uart_irq = ((uart_pending_status[0] & uart_enable_storage[0]) | (uart_pending_status[1] & uart_enable_storage[1]));
assign uart_tx_status = uart_tx_trigger;
assign uart_rx_status = uart_rx_trigger;
assign uart_tx_fifo_syncfifo_din = {uart_tx_fifo_fifo_in_last, uart_tx_fifo_fifo_in_first, uart_tx_fifo_fifo_in_payload_data};
assign {uart_tx_fifo_fifo_out_last, uart_tx_fifo_fifo_out_first, uart_tx_fifo_fifo_out_payload_data} = uart_tx_fifo_syncfifo_dout;
assign uart_tx_fifo_sink_ready = uart_tx_fifo_syncfifo_writable;
assign uart_tx_fifo_syncfifo_we = uart_tx_fifo_sink_valid;
assign uart_tx_fifo_fifo_in_first = uart_tx_fifo_sink_first;
assign uart_tx_fifo_fifo_in_last = uart_tx_fifo_sink_last;
assign uart_tx_fifo_fifo_in_payload_data = uart_tx_fifo_sink_payload_data;
assign uart_tx_fifo_source_valid = uart_tx_fifo_readable;
assign uart_tx_fifo_source_first = uart_tx_fifo_fifo_out_first;
assign uart_tx_fifo_source_last = uart_tx_fifo_fifo_out_last;
assign uart_tx_fifo_source_payload_data = uart_tx_fifo_fifo_out_payload_data;
assign uart_tx_fifo_re = uart_tx_fifo_source_ready;
assign uart_tx_fifo_syncfifo_re = (uart_tx_fifo_syncfifo_readable & ((~uart_tx_fifo_readable) | uart_tx_fifo_re));
assign uart_tx_fifo_level1 = (uart_tx_fifo_level0 + uart_tx_fifo_readable);
always @(*) begin
    uart_tx_fifo_wrport_adr <= 4'd0;
    if (uart_tx_fifo_replace) begin
        uart_tx_fifo_wrport_adr <= (uart_tx_fifo_produce - 1'd1);
    end else begin
        uart_tx_fifo_wrport_adr <= uart_tx_fifo_produce;
    end
end
assign uart_tx_fifo_wrport_dat_w = uart_tx_fifo_syncfifo_din;
assign uart_tx_fifo_wrport_we = (uart_tx_fifo_syncfifo_we & (uart_tx_fifo_syncfifo_writable | uart_tx_fifo_replace));
assign uart_tx_fifo_do_read = (uart_tx_fifo_syncfifo_readable & uart_tx_fifo_syncfifo_re);
assign uart_tx_fifo_rdport_adr = uart_tx_fifo_consume;
assign uart_tx_fifo_syncfifo_dout = uart_tx_fifo_rdport_dat_r;
assign uart_tx_fifo_rdport_re = uart_tx_fifo_do_read;
assign uart_tx_fifo_syncfifo_writable = (uart_tx_fifo_level0 != 5'd16);
assign uart_tx_fifo_syncfifo_readable = (uart_tx_fifo_level0 != 1'd0);
assign uart_rx_fifo_syncfifo_din = {uart_rx_fifo_fifo_in_last, uart_rx_fifo_fifo_in_first, uart_rx_fifo_fifo_in_payload_data};
assign {uart_rx_fifo_fifo_out_last, uart_rx_fifo_fifo_out_first, uart_rx_fifo_fifo_out_payload_data} = uart_rx_fifo_syncfifo_dout;
assign uart_rx_fifo_sink_ready = uart_rx_fifo_syncfifo_writable;
assign uart_rx_fifo_syncfifo_we = uart_rx_fifo_sink_valid;
assign uart_rx_fifo_fifo_in_first = uart_rx_fifo_sink_first;
assign uart_rx_fifo_fifo_in_last = uart_rx_fifo_sink_last;
assign uart_rx_fifo_fifo_in_payload_data = uart_rx_fifo_sink_payload_data;
assign uart_rx_fifo_source_valid = uart_rx_fifo_readable;
assign uart_rx_fifo_source_first = uart_rx_fifo_fifo_out_first;
assign uart_rx_fifo_source_last = uart_rx_fifo_fifo_out_last;
assign uart_rx_fifo_source_payload_data = uart_rx_fifo_fifo_out_payload_data;
assign uart_rx_fifo_re = uart_rx_fifo_source_ready;
assign uart_rx_fifo_syncfifo_re = (uart_rx_fifo_syncfifo_readable & ((~uart_rx_fifo_readable) | uart_rx_fifo_re));
assign uart_rx_fifo_level1 = (uart_rx_fifo_level0 + uart_rx_fifo_readable);
always @(*) begin
    uart_rx_fifo_wrport_adr <= 4'd0;
    if (uart_rx_fifo_replace) begin
        uart_rx_fifo_wrport_adr <= (uart_rx_fifo_produce - 1'd1);
    end else begin
        uart_rx_fifo_wrport_adr <= uart_rx_fifo_produce;
    end
end
assign uart_rx_fifo_wrport_dat_w = uart_rx_fifo_syncfifo_din;
assign uart_rx_fifo_wrport_we = (uart_rx_fifo_syncfifo_we & (uart_rx_fifo_syncfifo_writable | uart_rx_fifo_replace));
assign uart_rx_fifo_do_read = (uart_rx_fifo_syncfifo_readable & uart_rx_fifo_syncfifo_re);
assign uart_rx_fifo_rdport_adr = uart_rx_fifo_consume;
assign uart_rx_fifo_syncfifo_dout = uart_rx_fifo_rdport_dat_r;
assign uart_rx_fifo_rdport_re = uart_rx_fifo_do_read;
assign uart_rx_fifo_syncfifo_writable = (uart_rx_fifo_level0 != 5'd16);
assign uart_rx_fifo_syncfifo_readable = (uart_rx_fifo_level0 != 1'd0);
assign timer_zero_trigger = (timer_value == 1'd0);
assign timer_zero0 = timer_zero_status;
assign timer_zero1 = timer_zero_pending;
always @(*) begin
    timer_zero_clear <= 1'd0;
    if ((timer_pending_re & timer_pending_r)) begin
        timer_zero_clear <= 1'd1;
    end
end
assign timer_irq = (timer_pending_status & timer_enable_storage);
assign timer_zero_status = timer_zero_trigger;
assign {gpio_out_gpio_out7, gpio_out_gpio_out6, gpio_out_gpio_out5, gpio_out_gpio_out4, gpio_out_gpio_out3, gpio_out_gpio_out2, gpio_out_gpio_out1, gpio_out_gpio_out0} = gpio_out_storage;
always @(*) begin
    interface0_ack <= 1'd0;
    interface0_dat_r0 <= 32'd0;
    interface1_adr0 <= 14'd0;
    interface1_dat_w0 <= 32'd0;
    interface1_re0 <= 1'd0;
    interface1_we0 <= 1'd0;
    next_state <= 1'd0;
    next_state <= state;
    case (state)
        1'd1: begin
            interface0_ack <= 1'd1;
            interface0_dat_r0 <= interface1_dat_r0;
            next_state <= 1'd0;
        end
        default: begin
            interface1_dat_w0 <= interface0_dat_w0;
            if ((interface0_cyc & interface0_stb)) begin
                interface1_adr0 <= interface0_adr0;
                interface1_re0 <= ((~interface0_we0) & (interface0_sel != 1'd0));
                interface1_we0 <= (interface0_we0 & (interface0_sel != 1'd0));
                next_state <= 1'd1;
            end
        end
    endcase
end
assign csrbank0_sel = (interface0_adr1[13:9] == 1'd0);
assign csrbank0_reset0_r = interface0_dat_w1[1:0];
always @(*) begin
    csrbank0_reset0_re <= 1'd0;
    csrbank0_reset0_we <= 1'd0;
    if ((csrbank0_sel & (interface0_adr1[8:0] == 1'd0))) begin
        csrbank0_reset0_re <= interface0_we1;
        csrbank0_reset0_we <= interface0_re;
    end
end
assign csrbank0_scratch0_r = interface0_dat_w1;
always @(*) begin
    csrbank0_scratch0_re <= 1'd0;
    csrbank0_scratch0_we <= 1'd0;
    if ((csrbank0_sel & (interface0_adr1[8:0] == 1'd1))) begin
        csrbank0_scratch0_re <= interface0_we1;
        csrbank0_scratch0_we <= interface0_re;
    end
end
assign csrbank0_bus_errors_r = interface0_dat_w1;
always @(*) begin
    csrbank0_bus_errors_re <= 1'd0;
    csrbank0_bus_errors_we <= 1'd0;
    if ((csrbank0_sel & (interface0_adr1[8:0] == 2'd2))) begin
        csrbank0_bus_errors_re <= interface0_we1;
        csrbank0_bus_errors_we <= interface0_re;
    end
end
always @(*) begin
    soc_rst <= 1'd0;
    if (reset_re) begin
        soc_rst <= reset_storage[0];
    end
end
assign cpu_rst = reset_storage[1];
assign csrbank0_reset0_w = reset_storage;
assign csrbank0_scratch0_w = scratch_storage;
assign csrbank0_bus_errors_w = bus_errors_status;
assign bus_errors_we = csrbank0_bus_errors_we;
assign csrbank1_sel = (interface1_adr1[13:9] == 1'd1);
assign csrbank1_in_r = interface1_dat_w1[7:0];
always @(*) begin
    csrbank1_in_re <= 1'd0;
    csrbank1_in_we <= 1'd0;
    if ((csrbank1_sel & (interface1_adr1[8:0] == 1'd0))) begin
        csrbank1_in_re <= interface1_we1;
        csrbank1_in_we <= interface1_re1;
    end
end
assign csrbank1_in_w = gpio_in_status;
assign gpio_in_we = csrbank1_in_we;
assign csrbank2_sel = (interface2_adr[13:9] == 2'd2);
assign csrbank2_out0_r = interface2_dat_w[7:0];
always @(*) begin
    csrbank2_out0_re <= 1'd0;
    csrbank2_out0_we <= 1'd0;
    if ((csrbank2_sel & (interface2_adr[8:0] == 1'd0))) begin
        csrbank2_out0_re <= interface2_we;
        csrbank2_out0_we <= interface2_re;
    end
end
assign csrbank2_out0_w = gpio_out_storage;
assign csrbank3_sel = (interface3_adr[13:9] == 2'd3);
assign csrbank3_load0_r = interface3_dat_w;
always @(*) begin
    csrbank3_load0_re <= 1'd0;
    csrbank3_load0_we <= 1'd0;
    if ((csrbank3_sel & (interface3_adr[8:0] == 1'd0))) begin
        csrbank3_load0_re <= interface3_we;
        csrbank3_load0_we <= interface3_re;
    end
end
assign csrbank3_reload0_r = interface3_dat_w;
always @(*) begin
    csrbank3_reload0_re <= 1'd0;
    csrbank3_reload0_we <= 1'd0;
    if ((csrbank3_sel & (interface3_adr[8:0] == 1'd1))) begin
        csrbank3_reload0_re <= interface3_we;
        csrbank3_reload0_we <= interface3_re;
    end
end
assign csrbank3_en0_r = interface3_dat_w[0];
always @(*) begin
    csrbank3_en0_re <= 1'd0;
    csrbank3_en0_we <= 1'd0;
    if ((csrbank3_sel & (interface3_adr[8:0] == 2'd2))) begin
        csrbank3_en0_re <= interface3_we;
        csrbank3_en0_we <= interface3_re;
    end
end
assign csrbank3_update_value0_r = interface3_dat_w[0];
always @(*) begin
    csrbank3_update_value0_re <= 1'd0;
    csrbank3_update_value0_we <= 1'd0;
    if ((csrbank3_sel & (interface3_adr[8:0] == 2'd3))) begin
        csrbank3_update_value0_re <= interface3_we;
        csrbank3_update_value0_we <= interface3_re;
    end
end
assign csrbank3_value_r = interface3_dat_w;
always @(*) begin
    csrbank3_value_re <= 1'd0;
    csrbank3_value_we <= 1'd0;
    if ((csrbank3_sel & (interface3_adr[8:0] == 3'd4))) begin
        csrbank3_value_re <= interface3_we;
        csrbank3_value_we <= interface3_re;
    end
end
assign csrbank3_ev_status_r = interface3_dat_w[0];
always @(*) begin
    csrbank3_ev_status_re <= 1'd0;
    csrbank3_ev_status_we <= 1'd0;
    if ((csrbank3_sel & (interface3_adr[8:0] == 3'd5))) begin
        csrbank3_ev_status_re <= interface3_we;
        csrbank3_ev_status_we <= interface3_re;
    end
end
assign csrbank3_ev_pending_r = interface3_dat_w[0];
always @(*) begin
    csrbank3_ev_pending_re <= 1'd0;
    csrbank3_ev_pending_we <= 1'd0;
    if ((csrbank3_sel & (interface3_adr[8:0] == 3'd6))) begin
        csrbank3_ev_pending_re <= interface3_we;
        csrbank3_ev_pending_we <= interface3_re;
    end
end
assign csrbank3_ev_enable0_r = interface3_dat_w[0];
always @(*) begin
    csrbank3_ev_enable0_re <= 1'd0;
    csrbank3_ev_enable0_we <= 1'd0;
    if ((csrbank3_sel & (interface3_adr[8:0] == 3'd7))) begin
        csrbank3_ev_enable0_re <= interface3_we;
        csrbank3_ev_enable0_we <= interface3_re;
    end
end
assign csrbank3_load0_w = timer_load_storage;
assign csrbank3_reload0_w = timer_reload_storage;
assign csrbank3_en0_w = timer_en_storage;
assign csrbank3_update_value0_w = timer_update_value_storage;
assign csrbank3_value_w = timer_value_status;
assign timer_value_we = csrbank3_value_we;
assign timer_status_status = timer_zero0;
assign csrbank3_ev_status_w = timer_status_status;
assign timer_status_we = csrbank3_ev_status_we;
assign timer_pending_status = timer_zero1;
assign csrbank3_ev_pending_w = timer_pending_status;
assign timer_pending_we = csrbank3_ev_pending_we;
assign timer_zero2 = timer_enable_storage;
assign csrbank3_ev_enable0_w = timer_enable_storage;
assign csrbank4_sel = (interface4_adr[13:9] == 3'd4);
assign uart_rxtx_r = interface4_dat_w[7:0];
always @(*) begin
    uart_rxtx_re <= 1'd0;
    uart_rxtx_we <= 1'd0;
    if ((csrbank4_sel & (interface4_adr[8:0] == 1'd0))) begin
        uart_rxtx_re <= interface4_we;
        uart_rxtx_we <= interface4_re;
    end
end
assign csrbank4_txfull_r = interface4_dat_w[0];
always @(*) begin
    csrbank4_txfull_re <= 1'd0;
    csrbank4_txfull_we <= 1'd0;
    if ((csrbank4_sel & (interface4_adr[8:0] == 1'd1))) begin
        csrbank4_txfull_re <= interface4_we;
        csrbank4_txfull_we <= interface4_re;
    end
end
assign csrbank4_rxempty_r = interface4_dat_w[0];
always @(*) begin
    csrbank4_rxempty_re <= 1'd0;
    csrbank4_rxempty_we <= 1'd0;
    if ((csrbank4_sel & (interface4_adr[8:0] == 2'd2))) begin
        csrbank4_rxempty_re <= interface4_we;
        csrbank4_rxempty_we <= interface4_re;
    end
end
assign csrbank4_ev_status_r = interface4_dat_w[1:0];
always @(*) begin
    csrbank4_ev_status_re <= 1'd0;
    csrbank4_ev_status_we <= 1'd0;
    if ((csrbank4_sel & (interface4_adr[8:0] == 2'd3))) begin
        csrbank4_ev_status_re <= interface4_we;
        csrbank4_ev_status_we <= interface4_re;
    end
end
assign csrbank4_ev_pending_r = interface4_dat_w[1:0];
always @(*) begin
    csrbank4_ev_pending_re <= 1'd0;
    csrbank4_ev_pending_we <= 1'd0;
    if ((csrbank4_sel & (interface4_adr[8:0] == 3'd4))) begin
        csrbank4_ev_pending_re <= interface4_we;
        csrbank4_ev_pending_we <= interface4_re;
    end
end
assign csrbank4_ev_enable0_r = interface4_dat_w[1:0];
always @(*) begin
    csrbank4_ev_enable0_re <= 1'd0;
    csrbank4_ev_enable0_we <= 1'd0;
    if ((csrbank4_sel & (interface4_adr[8:0] == 3'd5))) begin
        csrbank4_ev_enable0_re <= interface4_we;
        csrbank4_ev_enable0_we <= interface4_re;
    end
end
assign csrbank4_txempty_r = interface4_dat_w[0];
always @(*) begin
    csrbank4_txempty_re <= 1'd0;
    csrbank4_txempty_we <= 1'd0;
    if ((csrbank4_sel & (interface4_adr[8:0] == 3'd6))) begin
        csrbank4_txempty_re <= interface4_we;
        csrbank4_txempty_we <= interface4_re;
    end
end
assign csrbank4_rxfull_r = interface4_dat_w[0];
always @(*) begin
    csrbank4_rxfull_re <= 1'd0;
    csrbank4_rxfull_we <= 1'd0;
    if ((csrbank4_sel & (interface4_adr[8:0] == 3'd7))) begin
        csrbank4_rxfull_re <= interface4_we;
        csrbank4_rxfull_we <= interface4_re;
    end
end
assign csrbank4_txfull_w = uart_txfull_status;
assign uart_txfull_we = csrbank4_txfull_we;
assign csrbank4_rxempty_w = uart_rxempty_status;
assign uart_rxempty_we = csrbank4_rxempty_we;
always @(*) begin
    uart_status_status <= 2'd0;
    uart_status_status[0] <= uart_tx0;
    uart_status_status[1] <= uart_rx0;
end
assign csrbank4_ev_status_w = uart_status_status;
assign uart_status_we = csrbank4_ev_status_we;
always @(*) begin
    uart_pending_status <= 2'd0;
    uart_pending_status[0] <= uart_tx1;
    uart_pending_status[1] <= uart_rx1;
end
assign csrbank4_ev_pending_w = uart_pending_status;
assign uart_pending_we = csrbank4_ev_pending_we;
assign uart_tx2 = uart_enable_storage[0];
assign uart_rx2 = uart_enable_storage[1];
assign csrbank4_ev_enable0_w = uart_enable_storage;
assign csrbank4_txempty_w = uart_txempty_status;
assign uart_txempty_we = csrbank4_txempty_we;
assign csrbank4_rxfull_w = uart_rxfull_status;
assign uart_rxfull_we = csrbank4_rxfull_we;
assign adr = interface1_adr0;
assign re = interface1_re0;
assign we = interface1_we0;
assign dat_w = interface1_dat_w0;
assign interface1_dat_r0 = dat_r;
assign interface0_adr1 = adr;
assign interface1_adr1 = adr;
assign interface2_adr = adr;
assign interface3_adr = adr;
assign interface4_adr = adr;
assign interface0_re = re;
assign interface1_re1 = re;
assign interface2_re = re;
assign interface3_re = re;
assign interface4_re = re;
assign interface0_we1 = we;
assign interface1_we1 = we;
assign interface2_we = we;
assign interface3_we = we;
assign interface4_we = we;
assign interface0_dat_w1 = dat_w;
assign interface1_dat_w1 = dat_w;
assign interface2_dat_w = dat_w;
assign interface3_dat_w = dat_w;
assign interface4_dat_w = dat_w;
assign dat_r = ((((interface0_dat_r1 | interface1_dat_r1) | interface2_dat_r) | interface3_dat_r) | interface4_dat_r);
always @(*) begin
    self0 <= 30'd0;
    case (grant)
        1'd0: begin
            self0 <= interface0_adapted_interface_adr;
        end
        default: begin
            self0 <= interface1_adapted_interface_adr;
        end
    endcase
end
always @(*) begin
    self1 <= 32'd0;
    case (grant)
        1'd0: begin
            self1 <= interface0_adapted_interface_dat_w;
        end
        default: begin
            self1 <= interface1_adapted_interface_dat_w;
        end
    endcase
end
always @(*) begin
    self2 <= 4'd0;
    case (grant)
        1'd0: begin
            self2 <= interface0_adapted_interface_sel;
        end
        default: begin
            self2 <= interface1_adapted_interface_sel;
        end
    endcase
end
always @(*) begin
    self3 <= 1'd0;
    case (grant)
        1'd0: begin
            self3 <= interface0_adapted_interface_cyc;
        end
        default: begin
            self3 <= interface1_adapted_interface_cyc;
        end
    endcase
end
always @(*) begin
    self4 <= 1'd0;
    case (grant)
        1'd0: begin
            self4 <= interface0_adapted_interface_stb;
        end
        default: begin
            self4 <= interface1_adapted_interface_stb;
        end
    endcase
end
always @(*) begin
    self5 <= 1'd0;
    case (grant)
        1'd0: begin
            self5 <= interface0_adapted_interface_we;
        end
        default: begin
            self5 <= interface1_adapted_interface_we;
        end
    endcase
end
always @(*) begin
    self6 <= 3'd0;
    case (grant)
        1'd0: begin
            self6 <= interface0_adapted_interface_cti;
        end
        default: begin
            self6 <= interface1_adapted_interface_cti;
        end
    endcase
end
always @(*) begin
    self7 <= 2'd0;
    case (grant)
        1'd0: begin
            self7 <= interface0_adapted_interface_bte;
        end
        default: begin
            self7 <= interface1_adapted_interface_bte;
        end
    endcase
end
assign rx_rx = multiregimpl01;
assign gpio_in_status = multiregimpl11;


//------------------------------------------------------------------------------
// Synchronous Logic
//------------------------------------------------------------------------------

always @(posedge sys_clk) begin
    case (grant)
        1'd0: begin
            if ((~request[0])) begin
                if (request[1]) begin
                    grant <= 1'd1;
                end
            end
        end
        1'd1: begin
            if ((~request[1])) begin
                if (request[0]) begin
                    grant <= 1'd0;
                end
            end
        end
    endcase
    slaves <= master;
    if (wait_1) begin
        if ((~done)) begin
            count <= (count - 1'd1);
        end
    end else begin
        count <= 20'd1000000;
    end
    if ((bus_errors != 32'd4294967295)) begin
        if (bus_error) begin
            bus_errors <= (bus_errors + 1'd1);
        end
    end
    basesoc_ram_bus_ack <= 1'd0;
    if (((basesoc_ram_bus_cyc & basesoc_ram_bus_stb) & ((~basesoc_ram_bus_ack) | basesoc_adr_burst))) begin
        basesoc_ram_bus_ack <= 1'd1;
    end
    ram_bus_ram_bus_ack <= 1'd0;
    if (((ram_bus_ram_bus_cyc & ram_bus_ram_bus_stb) & ((~ram_bus_ram_bus_ack) | ram_adr_burst))) begin
        ram_bus_ram_bus_ack <= 1'd1;
    end
    {tx_tick, tx_phase} <= 24'd9895604;
    if (tx_enable) begin
        {tx_tick, tx_phase} <= (tx_phase + 24'd9895604);
    end
    rs232phytx_state <= rs232phytx_next_state;
    if (tx_count_rs232phytx_next_value_ce0) begin
        tx_count <= tx_count_rs232phytx_next_value0;
    end
    if (serial_tx_rs232phytx_next_value_ce1) begin
        serial_tx <= serial_tx_rs232phytx_next_value1;
    end
    if (tx_data_rs232phytx_next_value_ce2) begin
        tx_data <= tx_data_rs232phytx_next_value2;
    end
    rx_rx_d <= rx_rx;
    {rx_tick, rx_phase} <= 32'd2147483648;
    if (rx_enable) begin
        {rx_tick, rx_phase} <= (rx_phase + 24'd9895604);
    end
    rs232phyrx_state <= rs232phyrx_next_state;
    if (rx_count_rs232phyrx_next_value_ce0) begin
        rx_count <= rx_count_rs232phyrx_next_value0;
    end
    if (rx_data_rs232phyrx_next_value_ce1) begin
        rx_data <= rx_data_rs232phyrx_next_value1;
    end
    if (uart_tx_clear) begin
        uart_tx_pending <= 1'd0;
    end
    uart_tx_trigger_d <= uart_tx_trigger;
    if ((uart_tx_trigger & (~uart_tx_trigger_d))) begin
        uart_tx_pending <= 1'd1;
    end
    if (uart_rx_clear) begin
        uart_rx_pending <= 1'd0;
    end
    uart_rx_trigger_d <= uart_rx_trigger;
    if ((uart_rx_trigger & (~uart_rx_trigger_d))) begin
        uart_rx_pending <= 1'd1;
    end
    if (uart_tx_fifo_syncfifo_re) begin
        uart_tx_fifo_readable <= 1'd1;
    end else begin
        if (uart_tx_fifo_re) begin
            uart_tx_fifo_readable <= 1'd0;
        end
    end
    if (((uart_tx_fifo_syncfifo_we & uart_tx_fifo_syncfifo_writable) & (~uart_tx_fifo_replace))) begin
        uart_tx_fifo_produce <= (uart_tx_fifo_produce + 1'd1);
    end
    if (uart_tx_fifo_do_read) begin
        uart_tx_fifo_consume <= (uart_tx_fifo_consume + 1'd1);
    end
    if (((uart_tx_fifo_syncfifo_we & uart_tx_fifo_syncfifo_writable) & (~uart_tx_fifo_replace))) begin
        if ((~uart_tx_fifo_do_read)) begin
            uart_tx_fifo_level0 <= (uart_tx_fifo_level0 + 1'd1);
        end
    end else begin
        if (uart_tx_fifo_do_read) begin
            uart_tx_fifo_level0 <= (uart_tx_fifo_level0 - 1'd1);
        end
    end
    if (uart_rx_fifo_syncfifo_re) begin
        uart_rx_fifo_readable <= 1'd1;
    end else begin
        if (uart_rx_fifo_re) begin
            uart_rx_fifo_readable <= 1'd0;
        end
    end
    if (((uart_rx_fifo_syncfifo_we & uart_rx_fifo_syncfifo_writable) & (~uart_rx_fifo_replace))) begin
        uart_rx_fifo_produce <= (uart_rx_fifo_produce + 1'd1);
    end
    if (uart_rx_fifo_do_read) begin
        uart_rx_fifo_consume <= (uart_rx_fifo_consume + 1'd1);
    end
    if (((uart_rx_fifo_syncfifo_we & uart_rx_fifo_syncfifo_writable) & (~uart_rx_fifo_replace))) begin
        if ((~uart_rx_fifo_do_read)) begin
            uart_rx_fifo_level0 <= (uart_rx_fifo_level0 + 1'd1);
        end
    end else begin
        if (uart_rx_fifo_do_read) begin
            uart_rx_fifo_level0 <= (uart_rx_fifo_level0 - 1'd1);
        end
    end
    if (timer_en_storage) begin
        if ((timer_value == 1'd0)) begin
            timer_value <= timer_reload_storage;
        end else begin
            timer_value <= (timer_value - 1'd1);
        end
    end else begin
        timer_value <= timer_load_storage;
    end
    if (timer_update_value_re) begin
        timer_value_status <= timer_value;
    end
    if (timer_zero_clear) begin
        timer_zero_pending <= 1'd0;
    end
    timer_zero_trigger_d <= timer_zero_trigger;
    if ((timer_zero_trigger & (~timer_zero_trigger_d))) begin
        timer_zero_pending <= 1'd1;
    end
    state <= next_state;
    interface0_dat_r1 <= 1'd0;
    if (csrbank0_sel) begin
        case (interface0_adr1[8:0])
            1'd0: begin
                interface0_dat_r1 <= csrbank0_reset0_w;
            end
            1'd1: begin
                interface0_dat_r1 <= csrbank0_scratch0_w;
            end
            2'd2: begin
                interface0_dat_r1 <= csrbank0_bus_errors_w;
            end
        endcase
    end
    if (csrbank0_reset0_re) begin
        reset_storage <= csrbank0_reset0_r;
    end
    reset_re <= csrbank0_reset0_re;
    if (csrbank0_scratch0_re) begin
        scratch_storage <= csrbank0_scratch0_r;
    end
    scratch_re <= csrbank0_scratch0_re;
    bus_errors_re <= csrbank0_bus_errors_re;
    interface1_dat_r1 <= 1'd0;
    if (csrbank1_sel) begin
        case (interface1_adr1[8:0])
            1'd0: begin
                interface1_dat_r1 <= csrbank1_in_w;
            end
        endcase
    end
    gpio_in_re <= csrbank1_in_re;
    interface2_dat_r <= 1'd0;
    if (csrbank2_sel) begin
        case (interface2_adr[8:0])
            1'd0: begin
                interface2_dat_r <= csrbank2_out0_w;
            end
        endcase
    end
    if (csrbank2_out0_re) begin
        gpio_out_storage <= csrbank2_out0_r;
    end
    gpio_out_re <= csrbank2_out0_re;
    interface3_dat_r <= 1'd0;
    if (csrbank3_sel) begin
        case (interface3_adr[8:0])
            1'd0: begin
                interface3_dat_r <= csrbank3_load0_w;
            end
            1'd1: begin
                interface3_dat_r <= csrbank3_reload0_w;
            end
            2'd2: begin
                interface3_dat_r <= csrbank3_en0_w;
            end
            2'd3: begin
                interface3_dat_r <= csrbank3_update_value0_w;
            end
            3'd4: begin
                interface3_dat_r <= csrbank3_value_w;
            end
            3'd5: begin
                interface3_dat_r <= csrbank3_ev_status_w;
            end
            3'd6: begin
                interface3_dat_r <= csrbank3_ev_pending_w;
            end
            3'd7: begin
                interface3_dat_r <= csrbank3_ev_enable0_w;
            end
        endcase
    end
    if (csrbank3_load0_re) begin
        timer_load_storage <= csrbank3_load0_r;
    end
    timer_load_re <= csrbank3_load0_re;
    if (csrbank3_reload0_re) begin
        timer_reload_storage <= csrbank3_reload0_r;
    end
    timer_reload_re <= csrbank3_reload0_re;
    if (csrbank3_en0_re) begin
        timer_en_storage <= csrbank3_en0_r;
    end
    timer_en_re <= csrbank3_en0_re;
    if (csrbank3_update_value0_re) begin
        timer_update_value_storage <= csrbank3_update_value0_r;
    end
    timer_update_value_re <= csrbank3_update_value0_re;
    timer_value_re <= csrbank3_value_re;
    timer_status_re <= csrbank3_ev_status_re;
    if (csrbank3_ev_pending_re) begin
        timer_pending_r <= csrbank3_ev_pending_r;
    end
    timer_pending_re <= csrbank3_ev_pending_re;
    if (csrbank3_ev_enable0_re) begin
        timer_enable_storage <= csrbank3_ev_enable0_r;
    end
    timer_enable_re <= csrbank3_ev_enable0_re;
    interface4_dat_r <= 1'd0;
    if (csrbank4_sel) begin
        case (interface4_adr[8:0])
            1'd0: begin
                interface4_dat_r <= uart_rxtx_w;
            end
            1'd1: begin
                interface4_dat_r <= csrbank4_txfull_w;
            end
            2'd2: begin
                interface4_dat_r <= csrbank4_rxempty_w;
            end
            2'd3: begin
                interface4_dat_r <= csrbank4_ev_status_w;
            end
            3'd4: begin
                interface4_dat_r <= csrbank4_ev_pending_w;
            end
            3'd5: begin
                interface4_dat_r <= csrbank4_ev_enable0_w;
            end
            3'd6: begin
                interface4_dat_r <= csrbank4_txempty_w;
            end
            3'd7: begin
                interface4_dat_r <= csrbank4_rxfull_w;
            end
        endcase
    end
    uart_txfull_re <= csrbank4_txfull_re;
    uart_rxempty_re <= csrbank4_rxempty_re;
    uart_status_re <= csrbank4_ev_status_re;
    if (csrbank4_ev_pending_re) begin
        uart_pending_r <= csrbank4_ev_pending_r;
    end
    uart_pending_re <= csrbank4_ev_pending_re;
    if (csrbank4_ev_enable0_re) begin
        uart_enable_storage <= csrbank4_ev_enable0_r;
    end
    uart_enable_re <= csrbank4_ev_enable0_re;
    uart_txempty_re <= csrbank4_txempty_re;
    uart_rxfull_re <= csrbank4_rxfull_re;
    if (sys_rst) begin
        reset_storage <= 2'd0;
        reset_re <= 1'd0;
        scratch_storage <= 32'd305419896;
        scratch_re <= 1'd0;
        bus_errors_re <= 1'd0;
        bus_errors <= 32'd0;
        basesoc_ram_bus_ack <= 1'd0;
        ram_bus_ram_bus_ack <= 1'd0;
        serial_tx <= 1'd1;
        tx_tick <= 1'd0;
        rx_tick <= 1'd0;
        rx_rx_d <= 1'd0;
        uart_txfull_re <= 1'd0;
        uart_rxempty_re <= 1'd0;
        uart_tx_pending <= 1'd0;
        uart_tx_trigger_d <= 1'd0;
        uart_rx_pending <= 1'd0;
        uart_rx_trigger_d <= 1'd0;
        uart_status_re <= 1'd0;
        uart_pending_re <= 1'd0;
        uart_pending_r <= 2'd0;
        uart_enable_storage <= 2'd0;
        uart_enable_re <= 1'd0;
        uart_txempty_re <= 1'd0;
        uart_rxfull_re <= 1'd0;
        uart_tx_fifo_readable <= 1'd0;
        uart_tx_fifo_level0 <= 5'd0;
        uart_tx_fifo_produce <= 4'd0;
        uart_tx_fifo_consume <= 4'd0;
        uart_rx_fifo_readable <= 1'd0;
        uart_rx_fifo_level0 <= 5'd0;
        uart_rx_fifo_produce <= 4'd0;
        uart_rx_fifo_consume <= 4'd0;
        timer_load_storage <= 32'd0;
        timer_load_re <= 1'd0;
        timer_reload_storage <= 32'd0;
        timer_reload_re <= 1'd0;
        timer_en_storage <= 1'd0;
        timer_en_re <= 1'd0;
        timer_update_value_storage <= 1'd0;
        timer_update_value_re <= 1'd0;
        timer_value_status <= 32'd0;
        timer_value_re <= 1'd0;
        timer_zero_pending <= 1'd0;
        timer_zero_trigger_d <= 1'd0;
        timer_status_re <= 1'd0;
        timer_pending_re <= 1'd0;
        timer_pending_r <= 1'd0;
        timer_enable_storage <= 1'd0;
        timer_enable_re <= 1'd0;
        timer_value <= 32'd0;
        gpio_in_re <= 1'd0;
        gpio_out_storage <= 8'd0;
        gpio_out_re <= 1'd0;
        grant <= 1'd0;
        slaves <= 3'd0;
        count <= 20'd1000000;
        rs232phytx_state <= 1'd0;
        rs232phyrx_state <= 1'd0;
        state <= 1'd0;
    end
    multiregimpl00 <= serial_rx;
    multiregimpl01 <= multiregimpl00;
    multiregimpl10 <= {gpio_in_gpio_in7, gpio_in_gpio_in6, gpio_in_gpio_in5, gpio_in_gpio_in4, gpio_in_gpio_in3, gpio_in_gpio_in2, gpio_in_gpio_in1, gpio_in_gpio_in0};
    multiregimpl11 <= multiregimpl10;
end


//------------------------------------------------------------------------------
// Specialized Logic
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// Memory storage: 16-words x 10-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: Sync | Mode: Read-First  | Write-Granularity: 10 
// Port 1 | Read: Sync  | Write: ---- | 
reg [9:0] storage[0:15];
reg [9:0] storage_dat0;
reg [9:0] storage_dat1;
always @(posedge sys_clk) begin
	if (uart_tx_fifo_wrport_we)
		storage[uart_tx_fifo_wrport_adr] <= uart_tx_fifo_wrport_dat_w;
	storage_dat0 <= storage[uart_tx_fifo_wrport_adr];
end
always @(posedge sys_clk) begin
	if (uart_tx_fifo_rdport_re)
		storage_dat1 <= storage[uart_tx_fifo_rdport_adr];
end
assign uart_tx_fifo_wrport_dat_r = storage_dat0;
assign uart_tx_fifo_rdport_dat_r = storage_dat1;


//------------------------------------------------------------------------------
// Memory storage_1: 16-words x 10-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: Sync | Mode: Read-First  | Write-Granularity: 10 
// Port 1 | Read: Sync  | Write: ---- | 
reg [9:0] storage_1[0:15];
reg [9:0] storage_1_dat0;
reg [9:0] storage_1_dat1;
always @(posedge sys_clk) begin
	if (uart_rx_fifo_wrport_we)
		storage_1[uart_rx_fifo_wrport_adr] <= uart_rx_fifo_wrport_dat_w;
	storage_1_dat0 <= storage_1[uart_rx_fifo_wrport_adr];
end
always @(posedge sys_clk) begin
	if (uart_rx_fifo_rdport_re)
		storage_1_dat1 <= storage_1[uart_rx_fifo_rdport_adr];
end
assign uart_rx_fifo_wrport_dat_r = storage_1_dat0;
assign uart_rx_fifo_rdport_dat_r = storage_1_dat1;


//------------------------------------------------------------------------------
// Instance serv_rf_top of serv_rf_top Module.
//------------------------------------------------------------------------------
serv_rf_top #(
	// Parameters.
	.RESET_PC (1'd0)
) serv_rf_top (
	// Inputs.
	.clk         (sys_clk),
	.i_dbus_ack  (dbus_ack),
	.i_dbus_rdt  (dbus_dat_r),
	.i_ibus_ack  (ibus_ack),
	.i_ibus_rdt  (ibus_dat_r),
	.i_rst       ((sys_rst | reset_1)),
	.i_timer_irq (1'd0),

	// Outputs.
	.o_dbus_adr  (dbus_adr),
	.o_dbus_cyc  (dbus_cyc),
	.o_dbus_dat  (dbus_dat_w),
	.o_dbus_sel  (dbus_sel),
	.o_dbus_we   (dbus_we),
	.o_ibus_adr  (ibus_adr),
	.o_ibus_cyc  (ibus_cyc)
);

//------------------------------------------------------------------------------
// Memory rom_grain0: 6032-words x 8-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: ---- | 
reg [7:0] rom_grain0[0:6031];
initial begin
	$readmemh("omdazz_c4_platform_rom_grain0.init", rom_grain0);
end
reg [7:0] rom_grain0_dat0;
always @(posedge sys_clk) begin
	rom_grain0_dat0 <= rom_grain0[basesoc_adr];
end
assign basesoc_dat_r[7:0] = rom_grain0_dat0;


//------------------------------------------------------------------------------
// Memory rom_grain1: 6032-words x 8-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: ---- | 
reg [7:0] rom_grain1[0:6031];
initial begin
	$readmemh("omdazz_c4_platform_rom_grain1.init", rom_grain1);
end
reg [7:0] rom_grain1_dat0;
always @(posedge sys_clk) begin
	rom_grain1_dat0 <= rom_grain1[basesoc_adr];
end
assign basesoc_dat_r[15:8] = rom_grain1_dat0;


//------------------------------------------------------------------------------
// Memory rom_grain2: 6032-words x 8-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: ---- | 
reg [7:0] rom_grain2[0:6031];
initial begin
	$readmemh("omdazz_c4_platform_rom_grain2.init", rom_grain2);
end
reg [7:0] rom_grain2_dat0;
always @(posedge sys_clk) begin
	rom_grain2_dat0 <= rom_grain2[basesoc_adr];
end
assign basesoc_dat_r[23:16] = rom_grain2_dat0;


//------------------------------------------------------------------------------
// Memory rom_grain3: 6032-words x 8-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: ---- | 
reg [7:0] rom_grain3[0:6031];
initial begin
	$readmemh("omdazz_c4_platform_rom_grain3.init", rom_grain3);
end
reg [7:0] rom_grain3_dat0;
always @(posedge sys_clk) begin
	rom_grain3_dat0 <= rom_grain3[basesoc_adr];
end
assign basesoc_dat_r[31:24] = rom_grain3_dat0;


//------------------------------------------------------------------------------
// Memory sram_grain0: 512-words x 8-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: Sync | Mode: Write-First | Write-Granularity: 8 
reg [7:0] sram_grain0[0:511];
initial begin
	$readmemh("omdazz_c4_platform_sram_grain0.init", sram_grain0);
end
reg [8:0] sram_grain0_adr0;
always @(posedge sys_clk) begin
	if (ram_we[0])
		sram_grain0[ram_adr] <= ram_dat_w[7:0];
	sram_grain0_adr0 <= ram_adr;
end
assign ram_dat_r[7:0] = sram_grain0[sram_grain0_adr0];


//------------------------------------------------------------------------------
// Memory sram_grain1: 512-words x 8-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: Sync | Mode: Write-First | Write-Granularity: 8 
reg [7:0] sram_grain1[0:511];
initial begin
	$readmemh("omdazz_c4_platform_sram_grain1.init", sram_grain1);
end
reg [8:0] sram_grain1_adr0;
always @(posedge sys_clk) begin
	if (ram_we[1])
		sram_grain1[ram_adr] <= ram_dat_w[15:8];
	sram_grain1_adr0 <= ram_adr;
end
assign ram_dat_r[15:8] = sram_grain1[sram_grain1_adr0];


//------------------------------------------------------------------------------
// Memory sram_grain2: 512-words x 8-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: Sync | Mode: Write-First | Write-Granularity: 8 
reg [7:0] sram_grain2[0:511];
initial begin
	$readmemh("omdazz_c4_platform_sram_grain2.init", sram_grain2);
end
reg [8:0] sram_grain2_adr0;
always @(posedge sys_clk) begin
	if (ram_we[2])
		sram_grain2[ram_adr] <= ram_dat_w[23:16];
	sram_grain2_adr0 <= ram_adr;
end
assign ram_dat_r[23:16] = sram_grain2[sram_grain2_adr0];


//------------------------------------------------------------------------------
// Memory sram_grain3: 512-words x 8-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: Sync | Mode: Write-First | Write-Granularity: 8 
reg [7:0] sram_grain3[0:511];
initial begin
	$readmemh("omdazz_c4_platform_sram_grain3.init", sram_grain3);
end
reg [8:0] sram_grain3_adr0;
always @(posedge sys_clk) begin
	if (ram_we[3])
		sram_grain3[ram_adr] <= ram_dat_w[31:24];
	sram_grain3_adr0 <= ram_adr;
end
assign ram_dat_r[31:24] = sram_grain3[sram_grain3_adr0];


//------------------------------------------------------------------------------
// Instance ars_cd_sys_ff0 of DFF Module.
//------------------------------------------------------------------------------
DFF ars_cd_sys_ff0(
	// Inputs.
	.clk  (sys_clk),
	.clrn (1'd1),
	.d    (1'd0),
	.prn  ((~(~reset))),

	// Outputs.
	.q    (ars_cd_sys_rst_meta)
);

//------------------------------------------------------------------------------
// Instance ars_cd_sys_ff1 of DFF Module.
//------------------------------------------------------------------------------
DFF ars_cd_sys_ff1(
	// Inputs.
	.clk  (sys_clk),
	.clrn (1'd1),
	.d    (ars_cd_sys_rst_meta),
	.prn  ((~(~reset))),

	// Outputs.
	.q    (sys_rst)
);

endmodule

// -----------------------------------------------------------------------------
//  Auto-Generated by LiteX on 2025-08-16 14:29:14.
//------------------------------------------------------------------------------
